export const ADD_ENERGY_SOURCE = "ADD_ENERGY_SOURCE";
export const SHOW_ENERGY_SOURCES = "SHOW_ENERGY_SOURCES";
export const LOAD_ENERGY_SOURCES = "LOAD_ENERGY_SOURCES";
export const SET_PRICE_FILTER = "SET_PRICE_FILTER";
export const SET_SOURCE_TYPE_FILTER = "SET_SOURCE_TYPE_FILTER";
export const SET_POWER = "SET_POWER";
export const SET_MODEL_FILTER = "SET_MODEL_FILTER";
